# =========================
# BASIC CONFIG
# =========================
spring.application.name=service-registry
server.port=8761

# =========================
# EUREKA SERVER CONFIG
# =========================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# IMPORTANT: Prevent self-preservation issues in dev
eureka.server.enable-self-preservation=false

# Faster registration (dev friendly)
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

# =========================
# OPTIONAL (CLEAN LOGS)
# =========================
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF